version: 2
project_name: gopulse

before:
  hooks:
    - go mod tidy

builds:
  - id: gopulse
    main: ./cmd/gopulse
    binary: gopulse
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      # Ensure these variables exist in your main package (see note below)
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: archives
    builds: [gopulse]
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: cploutarchou
    name: gopulse
  draft: false
  prerelease: false

sboms:
  - artifacts: archive